// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Context.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20191125065136_M002")]
    partial class M002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sphix.DataModels.Authorization.EmailVerificationDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsVerified");

                    b.Property<long?>("UserId");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(200);

                    b.Property<DateTime>("VerificationDate");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersEmailVerifications");
                });

            modelBuilder.Entity("Sphix.DataModels.Authorization.PhoneVerificationDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("IsVerified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10);

                    b.Property<DateTime>("VerificationDate");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("UsersPhoneVerification");
                });

            modelBuilder.Entity("Sphix.DataModels.Authorization.RestPasswordLinkDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsRequestHasUsed");

                    b.Property<bool>("IsRequestToRestPassword");

                    b.Property<long?>("UserId");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(200);

                    b.Property<DateTime>("VerificationDate");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRestPasswordLink");
                });

            modelBuilder.Entity("Sphix.DataModels.Authorization.RoleDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("RoleColor")
                        .HasMaxLength(50);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("RoleMaster");
                });

            modelBuilder.Entity("Sphix.DataModels.Communities.CommunityCatgoryDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasMaxLength(50);

                    b.Property<int>("CommunityId");

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("CommunitiesCatgories");
                });

            modelBuilder.Entity("Sphix.DataModels.Communities.CommunityDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasMaxLength(50);

                    b.Property<string>("CommunityUrl")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<int>("DisplayIndex");

                    b.Property<string>("FooterLinkText")
                        .HasMaxLength(200);

                    b.Property<string>("HeaderLogo")
                        .HasMaxLength(200);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("Sphix.DataModels.Communities.CommunityThemesDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackGroundImage")
                        .HasMaxLength(500);

                    b.Property<string>("Color")
                        .HasMaxLength(50);

                    b.Property<int>("CommunityId");

                    b.Property<string>("Description")
                        .HasMaxLength(1500);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("CommunityThemes");
                });

            modelBuilder.Entity("Sphix.DataModels.CountriesDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.HasIndex("CountryName")
                        .IsUnique()
                        .HasFilter("[CountryName] IS NOT NULL");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Sphix.DataModels.EmailInvitation.GroupEmailInvitationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AcceptedOn");

                    b.Property<long?>("CommunityGroupId");

                    b.Property<bool>("IsAccpeted");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<int>("ReSend");

                    b.Property<long?>("SentByUserId");

                    b.Property<DateTime>("SentOn");

                    b.Property<long>("SentTo");

                    b.Property<string>("ToEmailAddress");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupId");

                    b.HasIndex("SentByUserId");

                    b.ToTable("GroupEmailInvitations");
                });

            modelBuilder.Entity("Sphix.DataModels.Logger.LoggerDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("Detail");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100);

                    b.Property<string>("Message");

                    b.Property<string>("Source")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("LoggerManager");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserAssociationsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociationId");

                    b.Property<int?>("CommunityId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersAssociations");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserCommunitiesDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CommunityId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersCommunities");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserGroupsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommunityId");

                    b.Property<int>("GroupId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersGroups");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserInterestsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommunityId");

                    b.Property<int>("InterestId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersInterests");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserNotificationSettingsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<bool>("BlogSubscription");

                    b.Property<bool>("Comments");

                    b.Property<long>("CreatedBy");

                    b.Property<bool>("Followis");

                    b.Property<bool>("Like");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<long>("UpdatedBy");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsersNotificationSettings");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UsersLoginDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long>("CreatedBy");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastLoginDateTime");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Password");

                    b.Property<string>("PasswordSalt");

                    b.Property<long>("UpdatedBy");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("UsersLogin");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UsersProfileDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Company")
                        .HasMaxLength(200);

                    b.Property<int>("CountryId")
                        .HasMaxLength(50);

                    b.Property<long>("CreatedBy");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsCertifyTAndC");

                    b.Property<bool>("IsFinanciallyActive");

                    b.Property<bool>("IsKickstartarActive");

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("Latitude")
                        .HasMaxLength(20);

                    b.Property<string>("Longitude")
                        .HasMaxLength(20);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("ProfileLink")
                        .HasMaxLength(200);

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(500);

                    b.Property<string>("Street")
                        .HasMaxLength(50);

                    b.Property<long>("UpdatedBy");

                    b.Property<bool?>("UseMyLocation");

                    b.Property<long?>("UserId");

                    b.Property<string>("WebSite")
                        .HasMaxLength(200);

                    b.Property<string>("Zip")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ProfileLink")
                        .IsUnique()
                        .HasFilter("[ProfileLink] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("UsersProfile");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UsersRolesDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("RoleId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserSubCommunitiesDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Association");

                    b.Property<int?>("CommunityId");

                    b.Property<int>("GroupId");

                    b.Property<int>("Type1Id");

                    b.Property<int>("Type2ListId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersSubCommunities");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityArticles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<long>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ShareDocUrl")
                        .HasMaxLength(300);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityArticles");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<string>("CommunityGroupURL");

                    b.Property<int>("CommunityId");

                    b.Property<long>("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("DescriptionVideoUrl")
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsPublicGroup");

                    b.Property<bool>("IsPublish");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunitiesGroups");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityLiveEvents", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate");

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<long>("CreatedBy");

                    b.Property<string>("EDescription")
                        .HasMaxLength(2000);

                    b.Property<string>("EFrequency")
                        .HasMaxLength(50);

                    b.Property<DateTime>("EFromDate");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ETime")
                        .HasMaxLength(50);

                    b.Property<string>("ETimeDayName")
                        .HasMaxLength(50);

                    b.Property<string>("ETimeZone")
                        .HasMaxLength(50);

                    b.Property<string>("ETitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("EToDate");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsSingleEvent");

                    b.Property<int>("MaxAttendees");

                    b.Property<int>("Observers");

                    b.Property<int>("Participants");

                    b.Property<string>("Picture")
                        .HasMaxLength(300);

                    b.Property<long?>("UserId");

                    b.Property<string>("WhoCanAttend")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityLiveEvents");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityOpenOfficeHours", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AddHours");

                    b.Property<DateTime>("AddedDate");

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<long>("CreatedBy");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsFirstMeeting");

                    b.Property<bool>("IsMeetingTokenUsed");

                    b.Property<long>("LastSessionId");

                    b.Property<int>("MaxAttendees");

                    b.Property<string>("NextMeetingToken")
                        .HasMaxLength(100);

                    b.Property<string>("ODescription")
                        .HasMaxLength(2000);

                    b.Property<string>("OFrequency")
                        .HasMaxLength(50);

                    b.Property<DateTime>("OFromDate");

                    b.Property<string>("OName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OTime")
                        .HasMaxLength(50);

                    b.Property<string>("OTimeDayName")
                        .HasMaxLength(50);

                    b.Property<string>("OTimeZone")
                        .HasMaxLength(50);

                    b.Property<string>("OTitle")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("OToDate");

                    b.Property<long?>("UserId");

                    b.Property<string>("WhoCanAttend")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityOpenOfficeHours");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.UserCommunityGroupThemeDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<int>("CommunityTargetedGroupId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityGroupTheme");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.UserCommunityTargetedGroupsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<int>("CommunityTargetedGroupId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityTargetedGroups");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.Join.JoinCommunityGroupDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommunityGroupId");

                    b.Property<bool>("IsJoined");

                    b.Property<DateTime>("JoinDateTime");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserJoinCommunityGroup");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.Join.JoinEventMeetingDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsJoined");

                    b.Property<DateTime>("JoinDateTime");

                    b.Property<long?>("LiveEventId");

                    b.Property<string>("TimeZone");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LiveEventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserJoinEventMeetings");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.Join.JoinOpenHoursMeetingDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsJoined");

                    b.Property<DateTime>("JoinDateTime");

                    b.Property<long?>("OpenOfficeHoursId");

                    b.Property<string>("TimeZone");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OpenOfficeHoursId");

                    b.HasIndex("UserId");

                    b.ToTable("UserJoinCommunityOpenHourMeetings");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.PublishCommunityGroupLink.UserCommunityGroupPublishLinksDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CommunityGroupId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(200);

                    b.Property<DateTime>("VerificationDate");

                    b.HasKey("Id");

                    b.ToTable("UserCommunityGroupPublishLinks");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserArticleCommentsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ArticleId");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<long?>("CommentedById");

                    b.Property<DateTime>("CommentedDate");

                    b.Property<long>("DeletedBy");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeletedMessage");

                    b.Property<DateTime>("MessageDeletedDate");

                    b.Property<long>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CommentedById");

                    b.ToTable("UserArticleComments");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedAssociationsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociationId");

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityTargetedAssociations");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedInterestsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<int>("InterestId");

                    b.Property<bool>("IsActive");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityTargetedInterests");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedType1DataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<bool>("IsActive");

                    b.Property<int>("TypeId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityTargetedTypeOne");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedType2DataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CommunityGroupsId");

                    b.Property<bool>("IsActive");

                    b.Property<int>("TypeId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommunityGroupsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunityTargetedTypeTwo");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserEventCommentsDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<long?>("CommentedById");

                    b.Property<DateTime>("CommentedDate");

                    b.Property<long>("DeletedBy");

                    b.Property<long?>("EventsId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeletedMessage");

                    b.Property<DateTime>("MessageDeletedDate");

                    b.Property<long>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("CommentedById");

                    b.HasIndex("EventsId");

                    b.ToTable("UserEventComments");
                });

            modelBuilder.Entity("Sphix.DataModels.Authorization.EmailVerificationDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.Authorization.RestPasswordLinkDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.EmailInvitation.GroupEmailInvitationDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroup")
                        .WithMany()
                        .HasForeignKey("CommunityGroupId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentByUserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserAssociationsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.Communities.CommunityDataModel", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserCommunitiesDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserGroupsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.Communities.CommunityDataModel", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserInterestsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.Communities.CommunityDataModel", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserNotificationSettingsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UsersProfileDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UsersRolesDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.Authorization.RoleDataModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.User.UserSubCommunitiesDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.Communities.CommunityDataModel", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityArticles", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityLiveEvents", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.CommunityOpenOfficeHours", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.UserCommunityGroupThemeDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunities.UserCommunityTargetedGroupsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.Join.JoinCommunityGroupDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroup")
                        .WithMany()
                        .HasForeignKey("CommunityGroupId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.Join.JoinEventMeetingDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityLiveEvents", "LiveEvent")
                        .WithMany()
                        .HasForeignKey("LiveEventId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.Join.JoinOpenHoursMeetingDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityOpenOfficeHours", "OpenOfficeHours")
                        .WithMany()
                        .HasForeignKey("OpenOfficeHoursId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserArticleCommentsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityArticles", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "CommentedBy")
                        .WithMany()
                        .HasForeignKey("CommentedById");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedAssociationsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedInterestsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedType1DataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserCommunityTargetedType2DataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityGroupsDataModel", "CommunityGroups")
                        .WithMany()
                        .HasForeignKey("CommunityGroupsId");

                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sphix.DataModels.UserCommunitiesGroups.UserEventCommentsDataModel", b =>
                {
                    b.HasOne("Sphix.DataModels.User.UsersLoginDataModel", "CommentedBy")
                        .WithMany()
                        .HasForeignKey("CommentedById");

                    b.HasOne("Sphix.DataModels.UserCommunities.CommunityLiveEvents", "Events")
                        .WithMany()
                        .HasForeignKey("EventsId");
                });
#pragma warning restore 612, 618
        }
    }
}
